/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#define RCC_BASE_ADDRESS 				(0x40023800UL)
#define PWR_BASE_ADDRESS				(0x40007000UL)
#define GPIOA_BASE_ADDRESS				(0x40020000UL)

#define RCC_CLOCK_CONTROL_OFFSET		(0x00UL)
#define RCC_PLL_CLOCK_CONFIG_OFFSET		(0x04UL)
#define RCC_CLOCK_CONFIG_OFFSET			(0x08UL)
#define RCC_AHB1_CE_OFFSET 				(0x30UL)
#define RCC_APB1_CE_OFFSET 				(0x40UL)

#define PWR_CR_OFFSET					(0x00UL)
#define PWR_CSR_OFFSET					(0x04UL)

#define GPIO_Port_Mode_Offset			(0x00UL)
#define GPIO_Output_Type_Offset			(0x04UL) // Type
#define GPIO_Output_Speed_Offset		(0x08UL) // Speed
#define GPIO_PUPD_Offset				(0x0CUL) // Pull Up / Pull Down
#define GPIO_BSR_Offset					(0x18UL) // Bit Set / Reset
#define GPIO_AF_HIGH_Offset				(0x24UL)

#define PWR_CR_ADDRESS					(PWR_BASE_ADDRESS + PWR_CR_OFFSET)

#define RCC_CLOCK_CONTROL_ADDRESS		(RCC_BASE_ADDRESS + RCC_CLOCK_CONTROL_OFFSET)
#define RCC_PLL_ADDRESS					(RCC_BASE_ADDRESS + RCC_PLL_CLOCK_CONFIG_OFFSET)
#define RCC_CLOCK_CONFIG_ADDRESS		(RCC_BASE_ADDRESS + RCC_CLOCK_CONFIG_OFFSET)
#define RCC_AHB1_CE_ADDRESS				(RCC_BASE_ADDRESS + RCC_AHB1_CE_OFFSET)
#define RCC_APB1_CE_ADDRESS 			(RCC_BASE_ADDRESS + RCC_APB1_OFFSET)

#define GPIOA_Port_Mode_ADDRESS 		(GPIOA_BASE_ADDRESS + GPIO_Port_Mode_Offset)
#define GPIOA_Output_Type_ADDRESS 		(GPIOA_BASE_ADDRESS + GPIO_Output_Type_Offset)
#define GPIOA_Output_Speed_ADDRESS 		(GPIOA_BASE_ADDRESS + GPIO_Output_Speed_Offset)
#define GPIOA_PUPD_ADDRESS 				(GPIOA_BASE_ADDRESS + GPIO_PUPD_Offset)
#define GPIOA_BSR_ADDRESS 				(GPIOA_BASE_ADDRESS + GPIO_BSR_Offset)
#define GPIOA_AF_HIGH_ADDRESS			(GPIOA_BASE_ADDRESS + GPIO_AF_HIGH_Offset)

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	// Enable HSE
	uint32_t* clock_control_register = (uint32_t*) RCC_CLOCK_CONTROL_ADDRESS;
	(*clock_control_register) |= (1 << 16);

	// Wait for clock ready flag
	while(!( (*clock_control_register) & (1 << 17) ));

	// Set Clock Output to HSE
	uint32_t* clock_config_reg = (uint32_t*) RCC_CLOCK_CONFIG_ADDRESS;
	(*clock_config_reg) &= ~(0x1 << 21);
	(*clock_config_reg) |= (0x1 << 22);

	// Set MCO1 prescaler to 5 (25 / 5)
	(*clock_config_reg) |= (1 << 26);
	(*clock_config_reg) |= (1 << 25);
	(*clock_config_reg) |= (1 << 24);

	// Enable A8 Pin For MCO output
	uint32_t* AHB1_ce_address = (uint32_t*) RCC_AHB1_CE_ADDRESS;
	// Enable GPIOA clk
	(*AHB1_ce_address) |= (1 << 0);

	// Set GPIO Pin 8 As AF
	uint32_t* gpioa_port_mode_reg = (uint32_t*) GPIOA_Port_Mode_ADDRESS;
	(*gpioa_port_mode_reg) |= (1 << 17);

	// Set AF to AF0 (clear all bits)
	uint32_t* gpioa_af_high_reg = (uint32_t*) GPIOA_AF_HIGH_ADDRESS;
	(*gpioa_af_high_reg) &= ~(0xF << 0);

    /* Loop forever */
	for(;;);
}
