/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_Base_Address 				(0x40023800UL)
#define AHB1_Clock_Enable_OFFSET 		(0x30UL)

#define GPIO_C_Base_Address				(0x40020800UL)

#define GPIO_Port_Mode_Offset			(0x00UL)
#define GPIO_Output_Type_Offset			(0x04UL) // Type
#define GPIO_Output_Speed_Offset		(0x08UL) // Speed
#define GPIO_PUPD_Offset				(0x0CUL) // Pull Up / Pull Down
#define GPIO_BSR_Offset					(0x18UL) // Bit Set / Reset

#define AHB1_Clock_Enable_Addr (RCC_Base_Address + AHB1_Clock_Enable_OFFSET)

#define GPIO_C_Port_Mode_R 		(GPIO_C_Base_Address + GPIO_Port_Mode_Offset)
#define GPIO_C_Output_Type_R 	(GPIO_C_Base_Address + GPIO_Output_Type_Offset)
#define GPIO_C_Output_Speed_R 	(GPIO_C_Base_Address + GPIO_Output_Speed_Offset)
#define GPIO_C_PUPD_R 			(GPIO_C_Base_Address + GPIO_PUPD_Offset)
#define GPIO_C_BSR_R 			(GPIO_C_Base_Address + GPIO_BSR_Offset)

void wait(uint32_t time);

int main(void)
{
	// LED On C13

	// Enable GPIO C Clock
	uint32_t *ahb1PeripheralClockReg = (uint32_t*) AHB1_Clock_Enable_Addr;
	// Bit 2 for GPIOC
	*ahb1PeripheralClockReg |= (1 << 2);

	// Set GPIO mode register to 01 for general purpose output
	uint32_t *GPIOCModeR = (uint32_t*) GPIO_C_Port_Mode_R;
	*GPIOCModeR |= (1 << 26);

	// Set GPIO output type register to 0 for output push pull
	uint32_t *GPIOCOutputTypeR = (uint32_t*) GPIO_C_Output_Type_R;
	*GPIOCOutputTypeR &= ~(1 << 13);

	// Set GPIO output speed register to 10 for fast speed
	uint32_t *GPIOCOutputSpeedR = (uint32_t*) GPIO_C_Output_Speed_R;
	*GPIOCOutputSpeedR |= (1 << 27);

	// Set GPIO pull up pull down register to 00 as neither wanted
	uint32_t *GPIOCPUPDR = (uint32_t*) GPIO_C_PUPD_R;
	*GPIOCPUPDR &= ~((1 << 27) | (1 << 26));

	// Initialise location of bit set / reset register
	// this is a write only register and user set to power on reset off
	uint32_t *GPIOCBSRR = (uint32_t*) GPIO_C_BSR_R;

    /* Loop forever */
	for(;;){

		// Set bit
		*GPIOCBSRR |= (1 << 13);

		wait(2000000);

		// Reset bit
		*GPIOCBSRR |= (1 << 29);

		wait(2000000);
	}
}

void wait(uint32_t time){
	while(time--);
}

