/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>

#include "stm32f411xce.h"
#include "stm32f411xce_spi_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
 * PB9 SPI2_NSS - AF05
 * PB10 SPI2_SCK - AF05
 * PB14 SPI2_MISO - AF05
 * PB15 SPI2_MOSI - AF05
 */

void initSPIPins(void){
	GPIOB_PCLK_EN();

	// MOSI B15
	GPIOB->MODER |= (1 << 31);
	// MISO B14
	// GPIOB->MODER |= (1 << 29);
	// SCK B10
	GPIOB->MODER |= (1 << 21);
	// NSS B9
	GPIOB->MODER |= (1 << 19);

	GPIOB->OSPEEDR |= (0x3 << 30);
	// GPIOB->OSPEEDR |= (0x3 << 28);
	GPIOB->OSPEEDR |= (0x3 << 20);
	GPIOB->OSPEEDR |= (0x3 << 18);

	GPIOB->AFRH |= (0x5 << 28);
	// GPIOB->AFRH |= (0x5 << 24);
	GPIOB->AFRH |= (0x5 << 8);
	GPIOB->AFRH |= (0x5 << 4);
}

void SPI2_init(void){
	SPI_Handler_t SPI2handler;

	SPI2handler.SPIx = SPI2;
	SPI2handler.SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FD;
	SPI2handler.SPIConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;
	SPI2handler.SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV8;
	SPI2handler.SPIConfig.SPI_DFF = SPI_DFF_8BITS;
	SPI2handler.SPIConfig.SPI_CPOL = SPI_CPOL_LOW;
	SPI2handler.SPIConfig.SPI_CPHA = SPI_CPHA_LOW;
	SPI2handler.SPIConfig.SPI_SSM = SPI_SSM_DI;

	SPI_Init(&SPI2handler);
}

int main(void)
{
	char user_data[] = "Hello World";

	initSPIPins();
	SPI2_init();

	// When using software slave management
	// SPI_SSIControl(SPI2, ENABLE);

	SPI_SSOEControl(SPI2, ENABLE);

	SPI_PeripheralControl(SPI2, ENABLE);

	// Send length of data
	uint8_t datalength = strlen(user_data);
	SPI_Send_Data(SPI2, &datalength, 1);

	SPI_Send_Data(SPI2, (uint8_t*)user_data, strlen(user_data));

	while((SPI2->SR |= (1 << SPI_SR_BSY)) == 0);

	SPI_PeripheralControl(SPI2, DISABLE);

    /* Loop forever */
	for(;;);
}
